<?php
require_once dirname(__DIR__, 2) . '/app/bootstrap.php';
$conn = db_conn();
app_require('app/includes/session.php');
require_once app_path('app/config/database.php');
app_require('modules/family/portal_helpers.php');
ensure_family_portal_schema($conn);
require_family_dashboard_enabled($conn);
$family = require_family_portal_login($conn);
$householdId = (int)$family['household_id'];
$crops = fetch_all_assoc($conn, "SELECT c.*, (SELECT COUNT(*) FROM family_portal_updates fu WHERE fu.household_id=c.household_id AND fu.crop_id=c.crop_id AND fu.reviewed_status='Approved') AS approved_updates, (SELECT COALESCE(SUM(fu.points_awarded),0) FROM family_portal_updates fu WHERE fu.household_id=c.household_id AND fu.crop_id=c.crop_id AND fu.reviewed_status='Approved') AS earned_points, (SELECT MAX(fu.activity_date) FROM family_portal_updates fu WHERE fu.household_id=c.household_id AND fu.crop_id=c.crop_id AND fu.reviewed_status='Approved') AS last_activity_date FROM crops c WHERE c.household_id=" . $householdId . " ORDER BY c.crop_status='Active' DESC, c.crop_name ASC, c.crop_id DESC");
$logoUrl = system_logo_url($conn);
$appName = system_title($conn);
?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>My Crops - <?= e($appName) ?></title><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="<?= e(app_url('assets/css/app.css')) ?>"></head>
<body class="min-h-screen bg-slate-50 text-slate-800">
<header class="border-b border-slate-200 bg-white"><div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between gap-4"><div class="flex items-center gap-4"><img src="<?= e($logoUrl) ?>" alt="Logo" class="h-14 w-14 rounded-2xl object-cover"><div><div class="text-2xl font-black text-emerald-950"><?= e($appName) ?></div><div class="text-sm text-slate-500">Family crops</div></div></div><div class="flex gap-2"><a href="<?= e(app_url('modules/family/dashboard.php')) ?>" class="app-btn-outline">Back to dashboard</a><a href="<?= e(app_url('modules/family/timeline.php')) ?>" class="app-btn-outline">Timeline</a></div></div></header>
<div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 space-y-6">
<section class="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div class="text-sm text-slate-500">Your registered crops</div><h1 class="text-3xl font-black text-slate-900">My crops</h1><p class="mt-2 text-slate-500">Harvest and crop updates can only be submitted for the crops listed here.</p></section>
<section class="grid gap-4 md:grid-cols-3"><?php foreach ($crops as $crop): ?><article class="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between gap-3"><div class="font-black text-slate-900 text-xl"><?= e($crop['crop_name']) ?></div><?= format_status_badge($crop['crop_status'] ?: 'Unknown') ?></div><div class="mt-1 text-sm text-slate-500"><?= e($crop['variety'] ?: 'No variety') ?><?= !empty($crop['plot_name']) ? ' · Plot ' . e($crop['plot_name']) : '' ?></div><div class="mt-4 space-y-2 text-sm text-slate-600"><div>Trees: <strong><?= e((string)$crop['tree_count']) ?></strong></div><div>Fruiting: <strong><?= e($crop['fruiting_status'] ?: 'Unknown') ?></strong></div><div>Condition: <strong><?= e($crop['current_condition'] ?: 'Unknown') ?></strong></div><div>Approved updates: <strong><?= (int)$crop['approved_updates'] ?></strong></div><div>Points earned: <strong><?= e(rtrim(rtrim(number_format((float)$crop['earned_points'], 2, '.', ''), '0'), '.')) ?></strong></div><?php if (!empty($crop['last_activity_date'])): ?><div>Last approved activity: <strong><?= e(date('M d, Y', strtotime((string)$crop['last_activity_date']))) ?></strong></div><?php endif; ?><?php if (!empty($crop['planted_date'])): ?><div>Planted: <strong><?= e(date('M d, Y', strtotime((string)$crop['planted_date']))) ?></strong></div><?php endif; ?><?php if (!empty($crop['expected_fruiting_date'])): ?><div>Expected fruiting: <strong><?= e(date('M d, Y', strtotime((string)$crop['expected_fruiting_date']))) ?></strong></div><?php endif; ?><?php if (!empty($crop['area_sqm'])): ?><div>Area: <strong><?= e(number_format((float)$crop['area_sqm'], 2)) ?> sqm</strong></div><?php endif; ?></div><?php if (!empty($crop['remarks'])): ?><div class="mt-4 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-600"><?= e($crop['remarks']) ?></div><?php endif; ?></article><?php endforeach; ?><?php if (!$crops): ?><div class="rounded-[1.5rem] border border-slate-200 bg-white p-6 text-slate-500">No crops registered yet. Ask staff to register your crop first.</div><?php endif; ?></section>
</div></body></html>
