<?php
require_once dirname(__DIR__, 3) . '/app/bootstrap.php';
require_once __DIR__ . '/report_builder.php';

$conn = db_conn();
app_require('app/includes/auth.php');
require_role(['task_force','admin','mayor']);

$filters = report_build_filters($conn);
$columns = report_selected_columns_from_request();
$rows = report_fetch_rows($conn, $filters, null);
$available = report_available_columns();
$summary = report_summary_cards($rows);
$reportTitle = system_report_title($conn);
$reportSubtitle = system_report_subtitle($conn);
$generatedBy = current_user()['name'] ?? 'System User';
?><!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><?= e($reportTitle) ?></title>
<style>
:root{--text:#111827;--muted:#6b7280;--line:#d1d5db;--soft:#f8fafc;--accent:#215c38}
*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:var(--text);padding:24px;background:#fff}h1,h2,h3,p{margin:0}.hero{display:flex;justify-content:space-between;gap:18px;border:1px solid var(--line);border-radius:24px;padding:20px 22px;background:linear-gradient(135deg,#f6fbf7,#fff)}.eyebrow{font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--accent)}.subtitle{margin-top:10px;color:var(--muted);max-width:760px;line-height:1.5}.meta{min-width:240px;border:1px solid var(--line);border-radius:18px;padding:14px;background:#fff;color:var(--muted);font-size:13px;line-height:1.55}.chips{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0 14px}.chip{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:7px 11px;font-size:12px;background:#fff}.summary{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin:18px 0}.summary .box{border:1px solid var(--line);border-radius:18px;padding:14px;background:var(--soft)}.summary .label{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}.summary .value{font-size:28px;font-weight:800;margin-top:8px}.table-shell{border:1px solid var(--line);border-radius:22px;overflow:hidden;margin-top:18px}.table-head{padding:16px 18px;border-bottom:1px solid var(--line);background:var(--soft)}.table-head p{margin-top:6px;color:var(--muted);font-size:13px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border-bottom:1px solid #e5e7eb;padding:10px 12px;text-align:left;vertical-align:top}th{background:#f8fafc;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#475569}.right{text-align:right}.footer{margin-top:16px;color:var(--muted);font-size:12px;line-height:1.5}@media print{@page{size:landscape;margin:10mm}body{padding:0}.hero{break-inside:avoid}.summary{break-inside:avoid}.table-shell{border-radius:0;border-left:0;border-right:0}}
</style>
</head>
<body onload="window.print()">
    <section class="hero">
        <div>
            <div class="eyebrow">Print-ready report</div>
            <h1><?= e($reportTitle) ?></h1>
            <p class="subtitle"><?= e($reportSubtitle) ?> This layout uses your current report builder settings, so the preview, print output, and export package all stay aligned.</p>
        </div>
        <div class="meta">
            <div><strong>Generated by:</strong> <?= e($generatedBy) ?></div>
            <div><strong>Generated on:</strong> <?= e(date('F j, Y g:i A')) ?></div>
            <div><strong>Rows:</strong> <?= number_format(count($rows)) ?></div>
            <div><strong>Columns:</strong> <?= number_format(count($columns)) ?></div>
        </div>
    </section>

    <div class="chips">
        <?php if (($filters['barangay_id'] ?? 0) > 0): ?><span class="chip">Barangay filter applied</span><?php endif; ?>
        <?php if (($filters['qualification_status'] ?? '') !== ''): ?><span class="chip">Status: <?= e($filters['qualification_status']) ?></span><?php endif; ?>
        <?php if (($filters['profile_filter'] ?? '') !== ''): ?><span class="chip">Profile: <?= e(str_replace('_',' ', (string)$filters['profile_filter'])) ?></span><?php endif; ?>
        <span class="chip">View: <?= e(ucfirst((string)$filters['detail_mode'])) ?></span>
    </div>

    <div class="summary">
        <?php foreach ($summary as $item): ?>
            <div class="box">
                <div class="label"><?= e($item['label']) ?></div>
                <div class="value"><?= e($item['value']) ?></div>
            </div>
        <?php endforeach; ?>
    </div>

    <section class="table-shell">
        <div class="table-head">
            <h2>Preview before print</h2>
            <p>Only the selected builder columns are shown below.</p>
        </div>
        <div class="table-wrap">
            <table>
                <thead>
                    <tr>
                        <?php foreach ($columns as $column): ?>
                            <th class="<?= (($available[$column]['align'] ?? 'left') === 'right') ? 'right' : '' ?>"><?= e($available[$column]['label']) ?></th>
                        <?php endforeach; ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($rows as $row): ?>
                        <tr>
                            <?php foreach ($columns as $column): ?>
                                <td class="<?= (($available[$column]['align'] ?? 'left') === 'right') ? 'right' : '' ?>"><?= e(report_cell_display($column, $row)) ?></td>
                            <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                    <?php if (!$rows): ?>
                        <tr><td colspan="<?= count($columns) ?>">No matching report rows found.</td></tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </section>

    <div class="footer">Prepared for municipal presentation, planning, validation, and export review.</div>
</body>
</html>
