<?php
require_once dirname(__DIR__, 3) . '/app/bootstrap.php';
$conn = db_conn();
app_require('app/includes/auth.php');
require_role(['task_force','mayor','developer','admin']);
app_require('modules/family/portal_helpers.php');
app_require('app/includes/helpers/core.php');
ensure_family_portal_schema($conn);
$ready = fetch_all_assoc($conn, "SELECT h.household_head_name, h.household_code, b.barangay_name, q.score, q.qualification_status, COALESCE(s.total_points,0) AS family_points FROM households h LEFT JOIN barangays b ON b.barangay_id=h.barangay_id LEFT JOIN household_qualification q ON q.household_id=h.household_id LEFT JOIN household_points_summary s ON s.household_id=h.household_id ORDER BY q.score DESC, s.total_points DESC LIMIT 30");
$pending = fetch_all_assoc($conn, "SELECT b.barangay_name, COUNT(*) AS pending_total FROM family_portal_updates fu JOIN households h ON h.household_id=fu.household_id LEFT JOIN barangays b ON b.barangay_id=h.barangay_id WHERE fu.reviewed_status='Pending' GROUP BY b.barangay_name ORDER BY pending_total DESC");
app_require('app/includes/header.php');
?>
<section class="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div class="text-sm text-slate-500">Family contribution reporting</div><h1 class="text-3xl font-black text-slate-900">Family qualification reports</h1><div class="mt-6 grid gap-6 xl:grid-cols-2"><div><h2 class="text-xl font-black text-slate-900">Households by score</h2><div class="mt-4 space-y-3"><?php foreach ($ready as $row): ?><div class="rounded-2xl border border-slate-200 p-4"><div class="flex items-center justify-between gap-3"><div><div class="font-bold text-slate-900"><?= e($row['household_head_name']) ?></div><div class="text-sm text-slate-500"><?= e($row['household_code']) ?><?= !empty($row['barangay_name']) ? ' · ' . e($row['barangay_name']) : '' ?></div></div><div class="text-right"><div class="font-black text-emerald-700"><?= e(rtrim(rtrim(number_format((float)$row['score'], 2, '.', ''), '0'), '.')) ?></div><div class="text-sm text-slate-500">family pts <?= e(rtrim(rtrim(number_format((float)$row['family_points'], 2, '.', ''), '0'), '.')) ?></div></div></div><div class="mt-2"><?= format_status_badge($row['qualification_status'] ?: 'For Validation') ?></div></div><?php endforeach; ?></div></div><div><h2 class="text-xl font-black text-slate-900">Pending reviews by barangay</h2><div class="mt-4 space-y-3"><?php foreach ($pending as $row): ?><div class="rounded-2xl border border-slate-200 p-4 flex items-center justify-between gap-3"><div class="font-bold text-slate-900"><?= e($row['barangay_name'] ?: 'Unassigned') ?></div><div class="text-2xl font-black text-amber-600"><?= (int)$row['pending_total'] ?></div></div><?php endforeach; ?><?php if (!$pending): ?><div class="rounded-2xl border border-slate-200 p-4 text-slate-500">No pending family reviews right now.</div><?php endif; ?></div></div></div></section>
<?php app_require('app/includes/footer.php'); ?>
